### ISSUE TITLE
Inconsistent Documentation URL Endpoints (/points vs /objects) (/trendedAttributes/samples vs /attributes/samples)

### ISSUE THREAD

**Issue by bmeares** [metasys-server/api-docs#52]
Note: My problem is resolved, but I'm opening this issue in case someone later encounters a similar problem.

This might be only be on my end, perhaps a version issue, but I've noticed several inconsistencies with the endpoint structures outlined in the [v2 docs](https://metasys-server.github.io/api-landing/api/v2/) and with my use cases.

For example, the **Get Samples For An Object Attribute** section mentions `/points/{id}/trendedAttributes` for available attributeIds, but on our system the endpoint is `/objects/{id}/trendedAttributes`.

Additionally, the `/objects/{id}/trendedAttributes/{attributeId}/samples?{params}` endpoint on the API docs redirects my requests to `/objects/{id}/trendedAttributes` which thankfully provides a samplesUrl endpoint with the structure `/objects/{id}/attributes/samples?{params}`.

Once I had realized the issue, my problem was resolved, but I figured opening an issue could save someone else the hassle later down the road.

Below is a screenshot of the section where I noticed the problems. Both `/objects` and `/points` are listed on the page, which was easy to catch, but `/trendedAttributes` vs `/attributes` took more digging to resolve.
![screenshot](https://imgur.com/Qw8Eg7O.png)

**Comment by mgwelch** [comment]
Thanks @bmeares for the feedback. @DMahoney0 can you review this and address it?

**Comment by mgwelch** [comment]
> but `/trendedAttributes` vs `/attributes` took more digging to resolve.

I'm having some difficulty determining what issue you had with this. I think the answer lies in this paragraph:

> Additionally, the `/objects/{id}/trendedAttributes/{attributeId}/samples?{params}` endpoint on the API docs redirects my requests to `/objects/{id}/trendedAttributes` which thankfully provides a samplesUrl endpoint with the structure `/objects/{id}/attributes/samples?{params}`.

But I'm not quite following. @DMahoney0 please consider this issue as well in your review.

**Comment by michaelgwelch** [comment]
archiving this repo
